### PR TITLE
added support to replicate to local host without using ssh

### PR DESCRIPTION
**Pull request by the-vty**
Hi Joseph,

Thank you for your excellent zap tool. It is almost exactly what I need to make backups using zfs send/receive. Moreover FreeBSD has zap package!

In my case I have an offline backup disk connected to the same machine. It also could be SATA or USB drive. I want to backup locally and my patch enables it. If a hostname is "localhost" then it does "zfs send ... | zfs receive" directly without involving ssh.

cheers
victor

### CODE REVIEW

**Comment by Jehops** [comment]
Hi victor,

- What do you think about this for local replication: Instead of matching `localhost"|"127.0.0.1"|"::1`, determine if there is no `[user@]hostname:` before the parent dataset we are replicating to?

- Could you run your changes through http://shellcheck.net?  It might be best to maintain POSIX sh compatibility, but I am open to convincing arguments for why breaking POSIX is better.  Is `local` supported on, e.g., Illumos systems?

- I am wary of using eval.  The level of sanity checking to validate the input probably means it is better to avoid it.

Thank you,

Joseph

**Comment by the-vty** [comment]
Hi Joseph, sorry for not replying promptly.
I went with localhost to denote that it is not a remote backup. The goal was to be consistent and to make as less changes as possible. If you think that it would be better I can invest some more time in it.

My last commit makes the ShellCheck happy. Regarding the eval I do not think it is the evil. 
**ssh "$_sshto" "sh -c '${_tcmd}'"** does exactly the same as **eval "${_tcmd}"** but on the remote machine.

**Comment by Jehops** [comment]
Hi victor.  I will try to take close look this weekend.

**Comment by driesmp** [comment]
This would be a nice addition :)

**Comment by Jehops** [comment]
Sorry for the delay.  I have been under the weather and swamped catching up.  I will eventually get to this, I will just need a bit more time.  I just want to give it the attention it deserves (testing, etc.).

**Comment by the-vty** [comment]
Hi Joseph,

No problem at all. Get better and take your time.

wbr
/vty

**Comment by Jehops** [comment]
I appologize for the long delay getting back to you on this.

I spent some time looking over these changes. They look useful, but I am still concerned with the use of `eval`.  We do some checks on the variables supplied to `eval`, but I am not convinced we have covered all possible scenarios for harmful arbitrary code execution.  [BashFAQ/048](http://mywiki.wooledge.org/BashFAQ/048) describes some potential pitfalls.  Are you confident the issues described in the FAQ will not affect us?

I have an alternative implementation for local replication.  It is not sophisticated, and it is longer and has a few levels of nested conditionals, which I am not pleased with, but it avoids the use of `eval`.  I may push it to a branch here to get your thoughts, but it is still ugly and probably should be broken up into smaller functions.

**Comment by Jehops** [comment]
Based on your implementation, I pushed an alternative to the `local_backups` branch.  Could you test it and let me know if it meets your requirements for local replication?

**Comment by the-vty** [comment]
Great, Joseph! Thank you. I will work on it later. Sorry for not replying -
I have very busy months atm. I'm thinking of how to implement it without
eval. You're right. The remote backup box is the less threat than the
local. I mean although both eval and ssh remote command are equal evil, but
the local eval constitute more danger being executed on the source of the
backup.

cheers
/vty

**Comment by driesmp** [comment]
Just a side question, does local replication still require the format of "host:dataset"? And host should be 127.0.0.1, localhost or ::1? Can we not simply remove the first requirement and make it able to just set a local dataset to replicate to?

zfs set zap:rep="destinationdataset" sourcedataset 
instead of
zfs set zap:rep="localhost:destinationdataset" sourcedataset

I think its logical that if no host is specified, local replication should be done. Thoughts?

Also, @Jehops I tested your local replication branch and everything seems to be working as expected :)

**Comment by Jehops** [comment]
I pushed a change to not require a host when replicating locally.

**Comment by the-vty** [comment]
I tried it incrementally and on an empty filesystem. works like a charm.
The only thing is not updated is the zap help message. It should have the host part optional as well.

**Comment by Jehops** [comment]
The latest version, 0.8, adds support local replication.  Please let me know if you have any problems and thank you for submitting.

**Pull request closed without merging**
